#!/usr/bin/env bash

configs=()
configs+=('alias')
configs+=('misc')
configs+=('proxy')
configs+=('gpg')
env_root=~/.config/hendry/workstation/env

for config in "${configs[@]}"; do
	. $env_root/$config
done

# Lets have some fun!
$env_root/fun.py
