#!/usr/bin/env bash

configs=()
configs+=('alias')
configs+=('misc')
configs+=('proxy')
configs+=('gpg')
root=~/.config/hendry/workstation
env_root=${root}/env

for config in "${configs[@]}"; do
	. $env_root/$config
done

# Lets have some fun!
${root}/scripts/fun.py
